### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by fexra** [sbrekelmans/generator-info-standard#1]
Is this necessary?

**Comment by sbrekelmans** [comment]
Do you mean mandatory? No, none of these fields are.

**Comment by fexra** [comment]
> Do you mean mandatory? No, none of these fields are.

Gotcha. It appears to be a copy of the EOS node configuration form. Nothing wrong with that, but it begs to question of all those fields are necessary. 

```
node_name: Node/organization name
node_description
website: LTO Node website
ownership_disclosure: Full link to where it is,
email: Contact email
```
Should be enough imo with the exception of perhaps ``node_type`` and ``node_endpoint``. I was thinking for location, would it not be better to locate that by IP?

**Comment by sbrekelmans** [comment]
yeah scrap that entire comment; You are proposing to **keep** these fields and ditch the others.
I see a lot of people using their url to actually link to a social media profile (telegram mostly), personally I would like to link to several channels. Most importantly, an absolute way to link a specific node to a specific channel. The telegram groups for example can be confusing already, trying to find the correct chat for the correct leasing node, with all the deprecated channels, some abandoned leasing projects (it seems) etc...

**Comment by sbrekelmans** [comment]
Ok I removed the location. I kept the social information in for now. It's only a proposal after all. I'll let the LTO team decide how they want to exactly incorporate this, if they choose to do so. 
Thanks for your input @fexra ! closing this issue for now.
